spring.application.name=inventario

jwt.secret-key="RXN0YUVzVW5hQ2xhdmVTdXBlclNlY3JldGFQYXJhVHVJbnZlbnRhcmlvMjAyNkNvbk1hc0RlMjU2Qml0c0RlU2VndXJpZGFk"



# =========================================
# VARIABLES GLOBALES
# =========================================
user.admin = administrador
user.password = adminUTDI$26
password.reset = 1Nf0rm4t1c4$$

# =========================================
# CONEXION A LA BASE DE DATOS (PostgreSQL)
# =========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/inventario
spring.datasource.username=developer
spring.datasource.password=1nf0dgcp$$26

# =========================================
# CONFIGURACION DE JPA (Hibernate)
# =========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#VER LAS CONSULTAS GENERADAS EN LA CONSOLA DE SPRING
# spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#VER LAS CONSULTAS GENERADAS EN LA CONSOLA DE SPRING EN MODO DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# =========================================
# SPRING SECURITY
# =========================================
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

# =========================================
# DEVTOOLS
# =========================================
spring.devtools.restart.enabled=true
